feat: Shopping cart and edit cart
mpfan/Mini-Shopify pull request #64
Opened 2021-03-19 00:07 UTC by dershao

Adds a shopping cart functionality in the code.

Contains:
- Allows users to add to a shopping cart
- Shows items of the shopping cart in a shopping cart view
- Edit the quantities and remove items on the shopping cart view

It does not have:
- ability to save cart state with cookie/session

![shoppingcart](https://user-images.githubusercontent.com/13669499/111713021-24f2ee00-8825-11eb-8b72-8a9d6be17af4.png)

Closes #22 #21

2021-03-19 00:08 UTC, dershao commented on shopify-client/src/components/Header.vue
> +          <b-nav-item to="/app/cart">Cart ({{ cartItems }})</b-nav-item>
![header-cart](https://user-images.githubusercontent.com/13669499/111713294-b8c4ba00-8825-11eb-8490-110c258a69e1.png)

2021-03-19 12:24 UTC, mpfan requested changes
I know the PR stated that session/cookie is not implemented but I think it should be part of this feature. The implementation of the checkout will be dependent on how the cart tracking is done in this PR. This means we can't easily switch to session/cookie if we chose to use vuex to track the cart. The limitation with vuex is that state is lost upon refresh.

2021-03-19 12:56 UTC, dershao commented
> I know the PR stated that session/cookie is not implemented but I think it should be part of this feature. The implementation of the checkout will be dependent on how the cart tracking is done in this PR. This means we can't easily switch to session/cookie if we chose to use vuex to track the cart. The limitation with vuex is that state is lost upon refresh.

From my understanding of cookies, we can't store an object into the cookie. However, an object is useful for this shopping cart feature especially for counting the number of items of each item in the cart. So either way, I feel like some "cart object" will be present. The implementation I was going for was we would just serialize the cart object into a cookie so when the user comes back, it will check the cookie for a cart and deserialize it back into the vuex state.

Therefore, the roadmap for this feature would be something like this: 
- Use vuex to keep track of shopping cart state (no persistence)
- Add cookies support - cart object would be serialized to be stored in a cookie
- When user authentication is added, we would store the cart object into a session on our server and use some kind of session id in the cookie to retrieve the cart object we have stored in the database

Given this implementation, I figured I pushed this code now since for the checkout page, it would also probably use the vuex state to check for the cart object. It's just that in the future, there will be an additional step (e.g., if someone goes to the checkout page directly) it will check for a cart object in the cookies and deserialize that object into the vuex state.

2021-03-19 13:43 UTC, Souheil-Yazji approved these changes
LGTM

2021-03-19 13:43 UTC, Weebian commented on shopify-client/src/views/Cart.vue
> +        <b-row v-for="product in products" :key="product.name" class="b-row-cart-item">
nit-pick: should be on new lines:

:key=""
class=""

etc.

2021-03-19 17:36 UTC, Weebian approved these changes
+1

2021-03-20 22:17 UTC, mpfan approved these changes

2021-03-20 22:17 UTC, merged