bug-Center Aligns Header Logo
mpfan/Mini-Shopify pull request #68
Opened 2021-03-19 17:38 UTC by DwangDistracted

This change centers the header MiniShopify nav item.

![image](https://user-images.githubusercontent.com/23730000/111820841-57016000-88b8-11eb-840c-94fb9843fb69.png)

2021-03-19 20:02 UTC, Weebian approved these changes
+1

2021-03-20 01:28 UTC, Souheil-Yazji commented
Any change of fixing this?
Before:
![image](https://user-images.githubusercontent.com/35379392/111855221-f266f500-88f9-11eb-9e0b-9157dd80c494.png)

After:
![image](https://user-images.githubusercontent.com/35379392/111855234-03b00180-88fa-11eb-82a2-7e5c92680e7a.png)

2021-03-20 01:29 UTC, Souheil-Yazji requested changes
https://github.com/mpfan/Mini-Shopify/pull/68#issuecomment-803216666

2021-03-20 16:14 UTC, DwangDistracted commented
> Any chance of fixing this?
> Before:
> ![image](https://user-images.githubusercontent.com/35379392/111855221-f266f500-88f9-11eb-9e0b-9157dd80c494.png)
> 
> After:
> ![image](https://user-images.githubusercontent.com/35379392/111855234-03b00180-88fa-11eb-82a2-7e5c92680e7a.png)

Adjusted
![image](https://user-images.githubusercontent.com/23730000/111876570-af4a6780-8975-11eb-8af0-8fa3f3b81d76.png)
![image](https://user-images.githubusercontent.com/23730000/111876576-b83b3900-8975-11eb-9fd2-81e9b92fc4f3.png)

Still looks weird if the viewport is too small, but I don't think there's anything I can do about that.

2021-03-20 22:55 UTC, Souheil-Yazji submitted a review, later dismissed

2021-03-20 22:55 UTC, Weebian approved these changes
+1

2021-03-20 23:10 UTC, Weebian approved these changes
+1

2021-03-21 00:25 UTC, Souheil-Yazji approved these changes

2021-03-21 00:37 UTC, merged